# Generated by Django 3.2.16 on 2023-01-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='dep_description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='dep_name',
            new_name='course_name',
        ),
    ]
