# Generated by Django 3.2.16 on 2023-01-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230103_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainers_name', models.CharField(max_length=255)),
                ('trainers_spec', models.CharField(max_length=255)),
                ('trainers_image', models.ImageField(upload_to='trainers')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_phone', models.CharField(max_length=10)),
                ('s_email', models.EmailField(max_length=254)),
                ('admission_date', models.DateField()),
                ('started_on', models.DateField(auto_now=True)),
                ('trainers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainers')),
            ],
        ),
    ]
